name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/WisielecDiscordBot

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src/WisielecDiscordBot

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src/WisielecDiscordBot

    - name: Publish project
      run: dotnet publish -c Release -o publish
      working-directory: ./src/WisielecDiscordBot

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./src/WisielecDiscordBot/publish

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download published app
      uses: actions/download-artifact@v4
      with:
        name: published-app
        path: ./app

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./app
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/wisielec-discord-bot:latest